#!/bin/sh
set -e

src=$(pwd)
obj=$(mktemp -d)
cp -r . $obj
cd $obj

awk '
  /^  #include <README>/ { exit }
  { print }' \
    quickspec.cabal > tmp.cabal

sed 's/^$/./;s/^/  /' README >> tmp.cabal

awk '
  /^  #include <README>/ {
    x = 1
    next
  }
  x == 1 { print }' \
    quickspec.cabal >> tmp.cabal

mv tmp.cabal quickspec.cabal

cabal sdist --builddir=$src/dist
cd $src

rm -rf $obj
